name: Linting and tests

on:
  push:
    branches:
      - '**' # double to include slashes
    tags:
      - '*'
  pull_request:

# Cancel in-progress runs if a new run is triggered,
# except for main branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  linting:
    name: Linting using pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: neuroinformatics-unit/actions/lint@v2

  test:
    needs: [linting]
    name: Tests ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Run all supported Python versions on linux
        python-version: ["3.11"]
        os: [ubuntu-latest]
        # Include one windows and macos run
        include:
        - os: macos-latest
          python-version: "3.11"
        - os: windows-latest
          python-version: "3.11"
    steps:
      # Install ffmpeg for the relevant platform
      # by default, tests the latest release as
      # posted in https://ffmpeg.org/download.html#releases
      # (it is the only version avail in all mirrors)
      - uses: AnimMouse/setup-ffmpeg@v1

      # Run tests
      - uses: neuroinformatics-unit/actions/test@v2
        with:
          python-version: ${{ matrix.python-version }}

  # NOT IMPLEMENTED YET
  # check_tag:
  #   name: Check if trigger is a tag to a commit in main
  #   needs: [test]
  #   runs-on: ubuntu-latest
  #   outputs:
  #     tag_on_main: ${{ steps.check.outputs.tag_on_main }}
  #   steps:
  #     - uses: neuroinformatics-unit/actions/check_tag_on_main@v2
  #       id: check

  # build_sdist_wheels:
  #   name: Build source distribution
  #   needs: [test, check_tag]
  #   if: github.event_name == 'push' && needs.check_tag.outputs.tag_on_main == 'true'
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: neuroinformatics-unit/actions/build_sdist_wheels@v3

  # NOT IMPLEMENTED YET
  # upload_all:
  #   name: Publish build distributions
  #   needs: [build_sdist_wheels, check_tag]
  #   runs-on: ubuntu-latest
  #   environment: # use Trusted Publisher route
  #     name: pypi
  #     url: https://pypi.org/p/octron
  #   permissions:
  #     id-token: write # mandatory for trusted publishing
  #   steps:
  #   - uses: actions/download-artifact@v8
  #     with:
  #       name: artifact
  #       path: dist
  #   - uses: pypa/gh-action-pypi-publish@release/v1
